---
name: Build and test
on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: check repository code
        uses: actions/checkout@v3
      - name: install NodeJS
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: install the dependencies
        run: yarn install
      - name: fix linting config
        run: npx @eslint/migrate-config .eslintrc.json
      - name: fix possible linting errors
        run: yarn eslint . --fix
      - name: lint the project
        run: yarn eslint .
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: build
        uses: docker/build-push-action@v6
        with:
          context: .
          push: false
          tags: lisverhoeyen/webapp:latest