---
name: Build and test
on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: check repository code
        uses: actions/checkout@v3
      - name: install NodeJS
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: install the dependencies
        run: yarn install
      - name: lint the project
        run: yarn lint